const router = require('express').Router();

// Public legal pages — required as hosted URLs for the App Store / Play Store
// listing. Content mirrors the in-app legal pages (legal_pages.dart).

// Keep in step with `kLegalVersion` / `kLegalEffective` in legal_pages.dart —
// the app records acceptance against that version.
const EFFECTIVE = '23 July 2026';

function page(title, sections) {
  const body = sections
    .map((s) => `<h2>${s.h}</h2><p>${s.b}</p>`)
    .join('\n');
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>SolidCore AMS — ${title}</title>
<style>
  :root { color-scheme: dark; }
  body { margin:0; background:#0b0e13; color:#c8cdd8; font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; }
  .wrap { max-width:760px; margin:0 auto; padding:48px 22px 80px; }
  h1 { color:#fff; font-size:26px; letter-spacing:-0.3px; margin:0 0 4px; }
  .eff { color:#7b8494; font-size:13px; margin-bottom:32px; }
  h2 { color:#fff; font-size:17px; margin:28px 0 6px; }
  p { margin:0 0 4px; }
  a { color:#4aadff; }
  .foot { margin-top:48px; color:#7b8494; font-size:13px; text-align:center; }
</style></head>
<body><div class="wrap">
  <h1>${title}</h1>
  <div class="eff">Effective ${EFFECTIVE}</div>
  ${body}
  <div class="foot">© 2026 Tushar Dube</div>
</div></body></html>`;
}

const TERMS = [
  { h: '1. Acceptance of Terms', b: 'By downloading, accessing, or using the SolidCore application ("the App") you agree to be bound by these Terms &amp; Conditions. Ticking the "I have read and agree" box at sign-in records your acceptance of these Terms and of the Privacy Policy. If you do not agree, please discontinue use of the App.' },
  { h: '2. Use of the App', b: 'SolidCore is provided for general fitness, training, and informational purposes. You agree to use the App only for lawful purposes and not to misuse, reverse-engineer, or interfere with its normal operation.' },
  { h: '3. Important Medical Disclaimer — No Medical Advice', b: 'The services, text, data, graphics, charts, workload calculations, and metrics generated by this platform (including but not limited to acute-to-chronic workload ratios, wellness scores, body-composition estimates, and fatigue tracking) are for informational and sports-performance tracking purposes only.</p><p>This platform does not provide medical advice, diagnosis, or treatment. The contents of this app are not intended to be a substitute for professional medical advice, diagnosis, or rehabilitation. Always seek the advice of your physician, physiotherapist, or other qualified healthcare provider with any questions you may have regarding a medical condition or physical injury. Never disregard professional medical advice or delay in seeking it because of something you have read or interpreted on this platform.' },
  { h: '4. No Clinician-Patient Relationship', b: 'Your use of this software, including the submission of personal wellness data, training logs, or communication with any customer support, does not create a clinician-patient, doctor-patient, or therapist-patient relationship between you and the platform owner. The platform owner is acting strictly as a technology provider, not as your personal healthcare provider.' },
  { h: '5. Assumption of Risk &amp; Fit to Participate', b: 'You explicitly acknowledge that athletic training and sports performance tracking carry inherent risks of severe physical injury or illness. By using this platform, you certify that you are physically fit to participate in the training programs logged herein. You assume all risks associated with your training, and agree that the platform is merely a recording and analytical tool, not a monitoring system for medical safety.' },
  { h: '6. "As-Is" Data &amp; No Guarantee', b: 'The platform and its analytics are provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, express or implied, that the software will accurately predict or prevent injuries, overtraining, or performance drops. Human bodies react dynamically, and the software\'s outputs are strictly mathematical interpretations of data provided entirely by the user.' },
  { h: '7. Explicit Consent to Tracking', b: 'We only record your physical metrics, sleep, and fatigue data after you have given explicit consent by ticking the consent box shown at sign-in. Consent is opt-in, is never assumed, and can be withdrawn at any time from Privacy &amp; Security in the App. Withdrawing consent stops the related tracking going forward; you may also export or delete the data already recorded.' },
  { h: '8. Accounts', b: 'You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.' },
  { h: '9. Intellectual Property', b: 'All content, trademarks, and software in the App are owned by or licensed to SolidCore AMS and may not be copied or redistributed without permission.' },
  { h: '10. Limitation of Liability', b: 'To the maximum extent permitted by applicable law, in no event shall the Platform, its founders, or affiliates be liable for any direct, indirect, punitive, incidental, special, or consequential damages, including but not limited to personal injury, wrongful death, loss of athletic performance, or data loss. In any event, the total aggregate liability of the Platform for any claims arising out of these Terms shall be limited to the total amount actually paid by you to the Platform in the past 3 months.' },
  { h: '11. Changes to These Terms', b: 'We may update these Terms from time to time. Where the changes are material we will ask you to accept the updated Terms again. Continued use of the App after changes take effect constitutes acceptance of the revised Terms.' },
  { h: '12. Contact', b: 'Questions about these Terms can be sent to <a href="mailto:support@solidcoreats.com">support@solidcoreats.com</a>.' },
];

const PRIVACY = [
  { h: '1. Overview', b: 'This Privacy Policy explains how SolidCore AMS (operated by Tushar Dube) collects, uses, and protects your information when you use the App.' },
  { h: '2. Information We Collect', b: 'We collect the information you provide directly — such as your profile details and the measurements you enter — as well as the training, recovery, and body-composition data generated as you use the App. Physical metrics, sleep, and fatigue data are recorded only after you have given explicit consent (see section 5).' },
  { h: '3. On-Device Processing', b: 'Wherever possible, analyses such as body composition and camera-based movement assessments are processed on your device. Data stored on your device stays under your control.' },
  { h: '4. How We Use Your Information', b: 'Your information is used to calculate your scores, personalise insights, and improve the App. We do not sell your personal data.' },
  { h: '5. Explicit Consent', b: 'Tracking of your physical metrics, sleep, and fatigue is opt-in. It begins only after you tick the explicit "I agree" consent box shown at sign-in, and never by default. Camera-based analysis (posture, running, bowling) runs on your device and can be turned off at any time, and body-composition estimates ask for a separate acknowledgement before the first analysis. You can review, grant, or withdraw every consent at any time in Privacy &amp; Security; withdrawing consent disables the related feature going forward.' },
  { h: '6. Data Retention &amp; Deletion', b: 'You may delete your logs and account data at any time from within the App. Deleting your account permanently removes your data from our servers.' },
  { h: '7. Security', b: 'We use reasonable technical and organisational measures to protect your information, though no method of storage or transmission is completely secure.' },
  { h: '8. Contact', b: 'For privacy questions or requests, contact <a href="mailto:support@solidcoreats.com">support@solidcoreats.com</a>.' },
];

router.get('/terms', (_req, res) => res.type('html').send(page('Terms & Conditions', TERMS)));
router.get('/privacy', (_req, res) => res.type('html').send(page('Privacy Policy', PRIVACY)));

// Public, no-login-required pages for the two Play Store "Data safety"
// deletion links. Content must match what auth.js's DELETE routes actually
// do — DELETE /me/data wipes TrainingSession + BodyComposition (keeps the
// account); DELETE /me additionally deletes the User record itself.
const DELETE_DATA = [
  { h: 'In the app', b: 'Open SolidCore AMS, go to Profile → Privacy &amp; Security, and tap "Delete my data." This is available any time you are signed in and takes effect immediately.' },
  { h: 'Without the app', b: 'Email <a href="mailto:support@solidcoreats.com">support@solidcoreats.com</a> from the address registered to your account, with the subject "Delete my data." We verify the request and process it within 30 days.' },
  { h: 'What gets deleted', b: 'All recorded training sessions, wellness/recovery check-ins (sleep, soreness, fatigue, mood), and body-composition history.' },
  { h: 'What is kept', b: 'Your account itself (name, email, sign-in method) stays active so you can keep using the app and start logging fresh data immediately. Subscription/billing records are retained separately for financial record-keeping, as required by law.' },
];

const DELETE_ACCOUNT = [
  { h: 'In the app', b: 'Open SolidCore AMS, go to Profile → Privacy &amp; Security, and tap "Delete account." This is permanent and cannot be undone.' },
  { h: 'Without the app', b: 'Email <a href="mailto:support@solidcoreats.com">support@solidcoreats.com</a> from the address registered to your account, with the subject "Delete my account." We verify the request and process it within 30 days.' },
  { h: 'What gets deleted', b: 'Your entire account (name, email, sign-in credentials), plus all recorded training sessions, wellness/recovery check-ins, and body-composition history.' },
  { h: 'What is kept', b: 'Subscription/billing records are retained separately for financial record-keeping, as required by law. They are not linked to any of the personal or fitness data removed above once your account is deleted.' },
];

router.get('/delete-data', (_req, res) => res.type('html').send(page('Delete My Data — SolidCore AMS', DELETE_DATA)));
router.get('/delete-account', (_req, res) => res.type('html').send(page('Delete My Account — SolidCore AMS', DELETE_ACCOUNT)));

module.exports = router;
