import 'package:flutter/material.dart';
import '../core/theme.dart';

// ── Legal document scaffold ─────────────────────────────────────────────────
//
// Renders a titled legal document from a list of (heading, body) sections.
// Shared by the Terms & Conditions and Privacy Policy pages so both stay
// visually consistent with the rest of the app.

/// Version of the Terms & Privacy Policy currently shipped. Acceptance is
/// recorded against this value (see `LocalLogStore.acceptedLegalVersion`), so
/// bumping it re-prompts every user exactly once — keep it in step with
/// [kLegalEffective] and with `backend/routes/legal.js`.
const String kLegalVersion = '2026-07-23';

/// Human-readable form of [kLegalVersion], shown at the top of both documents.
const String kLegalEffective = '23 July 2026';

class LegalDocPage extends StatelessWidget {
  final String title;
  final String effective;
  final List<({String heading, String body})> sections;

  const LegalDocPage({
    super.key,
    required this.title,
    required this.effective,
    required this.sections,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: kBg,
      appBar: AppBar(
        backgroundColor: kBg,
        elevation: 0,
        iconTheme: IconThemeData(color: kTextPrimary),
        title: Text(title,
            style: TextStyle(fontSize: 13, fontWeight: FontWeight.w700,
                color: kTextSecondary, letterSpacing: 1.4)),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1),
          child: Divider(height: 1, color: kBorder),
        ),
      ),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(20, 20, 20, 40),
        children: [
          Text('Effective $effective',
              style: TextStyle(fontSize: 12, color: kTextMuted)),
          const SizedBox(height: 20),
          for (final s in sections) ...[
            Text(s.heading,
                style: TextStyle(fontSize: 15, fontWeight: FontWeight.w700,
                    color: kTextPrimary)),
            const SizedBox(height: 8),
            Text(s.body,
                style: TextStyle(fontSize: 13.5, color: kTextSecondary, height: 1.6)),
            const SizedBox(height: 22),
          ],
          const SizedBox(height: 4),
          Center(
            child: Text('© 2026 Tushar Dube',
                style: TextStyle(fontSize: 12, color: kTextMuted)),
          ),
        ],
      ),
    );
  }
}

// ── Terms & Conditions ──────────────────────────────────────────────────────

class TermsPage extends StatelessWidget {
  const TermsPage({super.key});

  @override
  Widget build(BuildContext context) => const LegalDocPage(
    title: 'TERMS & CONDITIONS',
    effective: kLegalEffective,
    sections: [
      (
        heading: '1. Acceptance of Terms',
        body: 'By downloading, accessing, or using the SolidCore application '
            '("the App") you agree to be bound by these Terms & Conditions. '
            'Ticking the "I have read and agree" box at sign-in records your '
            'acceptance of these Terms and of the Privacy Policy. If you do not '
            'agree, please discontinue use of the App.',
      ),
      (
        heading: '2. Use of the App',
        body: 'SolidCore is provided for general fitness, training, and '
            'informational purposes. You agree to use the App only for lawful '
            'purposes and not to misuse, reverse-engineer, or interfere with '
            'its normal operation.',
      ),
      (
        heading: '3. Important Medical Disclaimer — No Medical Advice',
        body: 'The services, text, data, graphics, charts, workload '
            'calculations, and metrics generated by this platform (including '
            'but not limited to acute-to-chronic workload ratios, wellness '
            'scores, body-composition estimates, and fatigue tracking) are for '
            'informational and sports-performance tracking purposes only.\n\n'
            'This platform does not provide medical advice, diagnosis, or '
            'treatment. The contents of this app are not intended to be a '
            'substitute for professional medical advice, diagnosis, or '
            'rehabilitation. Always seek the advice of your physician, '
            'physiotherapist, or other qualified healthcare provider with any '
            'questions you may have regarding a medical condition or physical '
            'injury. Never disregard professional medical advice or delay in '
            'seeking it because of something you have read or interpreted on '
            'this platform.',
      ),
      (
        heading: '4. No Clinician-Patient Relationship',
        body: 'Your use of this software, including the submission of personal '
            'wellness data, training logs, or communication with any customer '
            'support, does not create a clinician-patient, doctor-patient, or '
            'therapist-patient relationship between you and the platform owner. '
            'The platform owner is acting strictly as a technology provider, not '
            'as your personal healthcare provider.',
      ),
      (
        heading: '5. Assumption of Risk & Fit to Participate',
        body: 'You explicitly acknowledge that athletic training and sports '
            'performance tracking carry inherent risks of severe physical injury '
            'or illness. By using this platform, you certify that you are '
            'physically fit to participate in the training programs logged '
            'herein. You assume all risks associated with your training, and '
            'agree that the platform is merely a recording and analytical tool, '
            'not a monitoring system for medical safety.',
      ),
      (
        heading: '6. "As-Is" Data & No Guarantee',
        body: 'The platform and its analytics are provided on an "AS IS" and "AS '
            'AVAILABLE" basis. We make no warranties, express or implied, that '
            'the software will accurately predict or prevent injuries, '
            'overtraining, or performance drops. Human bodies react dynamically, '
            'and the software\'s outputs are strictly mathematical '
            'interpretations of data provided entirely by the user.',
      ),
      (
        heading: '7. Explicit Consent to Tracking',
        body: 'We only record your physical metrics, sleep, and fatigue data '
            'after you have given explicit consent by ticking the consent box '
            'shown at sign-in. Consent is opt-in, is never assumed, and can be '
            'withdrawn at any time from Privacy & Security in the App. '
            'Withdrawing consent stops the related tracking going forward; you '
            'may also export or delete the data already recorded.',
      ),
      (
        heading: '8. Accounts',
        body: 'You are responsible for maintaining the confidentiality of your '
            'account credentials and for all activity that occurs under your '
            'account.',
      ),
      (
        heading: '9. Intellectual Property',
        body: 'All content, trademarks, and software in the App are owned by or '
            'licensed to SolidCoreATS and may not be copied or '
            'redistributed without permission.',
      ),
      (
        heading: '10. Limitation of Liability',
        body: 'To the maximum extent permitted by applicable law, in no event '
            'shall the Platform, its founders, or affiliates be liable for any '
            'direct, indirect, punitive, incidental, special, or consequential '
            'damages, including but not limited to personal injury, wrongful '
            'death, loss of athletic performance, or data loss. In any event, '
            'the total aggregate liability of the Platform for any claims '
            'arising out of these Terms shall be limited to the total amount '
            'actually paid by you to the Platform in the past 3 months.',
      ),
      (
        heading: '11. Changes to These Terms',
        body: 'We may update these Terms from time to time. Where the changes '
            'are material we will ask you to accept the updated Terms again. '
            'Continued use of the App after changes take effect constitutes '
            'acceptance of the revised Terms.',
      ),
      (
        heading: '12. Contact',
        body: 'Questions about these Terms can be sent to support@solidcoreats.com.',
      ),
    ],
  );
}

// ── Privacy Policy ──────────────────────────────────────────────────────────

class PrivacyPolicyPage extends StatelessWidget {
  const PrivacyPolicyPage({super.key});

  @override
  Widget build(BuildContext context) => const LegalDocPage(
    title: 'PRIVACY POLICY',
    effective: kLegalEffective,
    sections: [
      (
        heading: '1. Overview',
        body: 'This Privacy Policy explains how SolidCoreATS (operated '
            'by Tushar Dube) collects, uses, and protects your information when you use the App.',
      ),
      (
        heading: '2. Information We Collect',
        body: 'We collect the information you provide directly — such as your '
            'profile details and the measurements you enter — as well as the '
            'training, recovery, and body-composition data generated as you use '
            'the App. Physical metrics, sleep, and fatigue data are recorded '
            'only after you have given explicit consent (see section 5).',
      ),
      (
        heading: '3. On-Device Processing',
        body: 'Wherever possible, analyses such as body composition and '
            'camera-based movement assessments are processed on your device. '
            'Data stored on your device stays under your control.',
      ),
      (
        heading: '4. How We Use Your Information',
        body: 'Your information is used to calculate your scores, personalise '
            'insights, and improve the App. We do not sell your personal data.',
      ),
      (
        heading: '5. Explicit Consent',
        body: 'Tracking of your physical metrics, sleep, and fatigue is opt-in. '
            'It begins only after you tick the explicit "I agree" consent box '
            'shown at sign-in, and never by default. Camera-based analysis '
            '(posture, running, bowling) runs on your device and can be turned '
            'off at any time, and body-composition estimates ask for a separate '
            'acknowledgement before the first analysis. You can review, grant, '
            'or withdraw every consent at any time in Privacy & Security; '
            'withdrawing consent disables the related feature going forward.',
      ),
      (
        heading: '6. Data Retention & Deletion',
        body: 'You may delete your logs and account data at any time from within '
            'the App. Deleted data is removed from your device.',
      ),
      (
        heading: '7. Security',
        body: 'We use reasonable technical and organisational measures to protect '
            'your information, though no method of storage or transmission is '
            'completely secure.',
      ),
      (
        heading: '8. Contact',
        body: 'For privacy questions or requests, contact support@solidcoreats.com.',
      ),
    ],
  );
}
